import React, { useEffect, useState } from "react";
import { ActivityIndicator, Alert, Modal, SafeAreaView, ScrollView, StyleSheet, TouchableOpacity, View } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { useLocalSearchParams, useRouter } from "expo-router";
import QRCode from "react-native-qrcode-svg";
import { getTripBooking, TripBooking } from "../../services/tripBookingsApi";
import { API_BASE_URL } from "../../config/env";
import { LocalizedText as Text } from "../../utils/i18n";

export default function ConfirmScreen() {
  const router = useRouter();
  const params = useLocalSearchParams<{ bookingId?: string; tripDetails?: string }>();
  const fallback = params.tripDetails ? JSON.parse(params.tripDetails) : {};
  const bookingId = Number(params.bookingId || fallback.bookingId || fallback.id);
  const [booking, setBooking] = useState<TripBooking | null>(null);
  const [loading, setLoading] = useState(true);
  const [ticketVisible, setTicketVisible] = useState(false);

  useEffect(() => {
    if (!bookingId) { setLoading(false); return; }
    getTripBooking(bookingId).then(setBooking).catch((error: any) => Alert.alert("Booking unavailable", error?.message || "Could not load the saved booking.")).finally(() => setLoading(false));
  }, [bookingId]);

  if (loading) return <SafeAreaView style={styles.center}><ActivityIndicator size="large" color="#2563EB" /><Text style={styles.muted}>Loading your confirmed booking...</Text></SafeAreaView>;
  if (!booking) return <SafeAreaView style={styles.center}><Text style={styles.muted}>The booking could not be loaded.</Text><TouchableOpacity style={styles.button} onPress={() => router.replace("/tabs")}><Text style={styles.buttonText}>Return Home</Text></TouchableOpacity></SafeAreaView>;

  const verifyUrl = `${API_BASE_URL}/api/trips/verify/${booking.id}`;
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><View style={styles.header}><TouchableOpacity onPress={() => router.replace("/tabs")}><Ionicons name="chevron-back" size={22} color="#111827" /></TouchableOpacity><Text style={styles.headerTitle}>Booking #{booking.id}</Text><View style={{ width: 22 }} /></View><View style={styles.success}><View style={styles.successIcon}><Ionicons name="checkmark" size={40} color="white" /></View><Text style={styles.successTitle}>Booking Confirmed</Text><Text style={styles.muted}>Your advance payment is recorded and your ticket is ready.</Text></View><View style={styles.progress}><View style={styles.track}><View style={styles.fill} /></View><Text style={styles.progressText}>Sent  ·  Negotiation  ·  Payment  ·  Confirmed</Text></View><View style={styles.card}><Text style={styles.ref}>REF: #{booking.id}</Text><Text style={styles.route}>{booking.startLocation} → {booking.destination}</Text><View style={styles.divider} /><Row label="Departure" value={booking.startDate} /><Row label="Return" value={booking.returnDate || "Same day"} /><Row label="Passengers" value={String(booking.passengerCount)} /><Row label="Bus" value={booking.busNumber || "Assigned bus"} /><Row label="Advance paid" value={`LKR ${Number(booking.advancePayment).toLocaleString()}`} /></View><TouchableOpacity style={styles.button} onPress={() => setTicketVisible(true)}><Ionicons name="ticket-outline" size={20} color="white" /><Text style={styles.buttonText}>View Digital Ticket</Text></TouchableOpacity><TouchableOpacity style={styles.homeButton} onPress={() => router.replace("/tabs")}><Text style={styles.homeText}>Return to Home</Text></TouchableOpacity><Modal visible={ticketVisible} transparent animationType="fade"><View style={styles.overlay}><View style={styles.ticket}><View style={styles.ticketHeader}><Text style={styles.brand}>TRACKNGo</Text><Text style={styles.eTicket}>E-TICKET</Text></View><Text style={styles.ticketRoute}>{booking.startLocation} → {booking.destination}</Text><Row label="DATE" value={booking.startDate} /><Row label="BOOKING ID" value={`#${booking.id}`} /><Row label="BUS" value={booking.busNumber || "Assigned bus"} /><View style={styles.qr}><QRCode value={verifyUrl} size={180} /><Text style={styles.qrText}>Scan to verify this booking</Text></View><TouchableOpacity onPress={() => setTicketVisible(false)} style={styles.close}><Text style={styles.closeText}>Close</Text></TouchableOpacity></View></View></Modal></ScrollView></SafeAreaView>;
}

function Row({ label, value }: { label: string; value: string }) { return <View style={styles.row}><Text style={styles.rowLabel}>{label}</Text><Text style={styles.rowValue}>{value}</Text></View>; }

const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: "#F6F7FB" }, content: { padding: 16, paddingBottom: 36 }, center: { flex: 1, justifyContent: "center", alignItems: "center", padding: 24, backgroundColor: "#F6F7FB" }, header: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 20 }, headerTitle: { fontSize: 16, fontWeight: "600", color: "#111827" }, success: { alignItems: "center", marginBottom: 22 }, successIcon: { width: 80, height: 80, borderRadius: 40, backgroundColor: "#22C55E", justifyContent: "center", alignItems: "center" }, successTitle: { color: "#111827", fontSize: 22, fontWeight: "bold", marginTop: 16 }, muted: { color: "#6B7280", fontSize: 13, marginTop: 8, textAlign: "center" }, progress: { marginBottom: 20 }, track: { height: 6, backgroundColor: "#E5E7EB", borderRadius: 8 }, fill: { height: 6, width: "100%", backgroundColor: "#2563EB", borderRadius: 8 }, progressText: { color: "#2563EB", fontSize: 11, textAlign: "center", marginTop: 8 }, card: { backgroundColor: "white", borderRadius: 16, padding: 20, elevation: 2, marginBottom: 16 }, ref: { color: "#94A3B8", fontSize: 12, fontWeight: "700" }, route: { color: "#111827", fontSize: 18, fontWeight: "bold", marginTop: 5 }, divider: { height: 1, backgroundColor: "#F1F5F9", marginVertical: 16 }, row: { flexDirection: "row", justifyContent: "space-between", marginBottom: 12, gap: 16 }, rowLabel: { color: "#64748B", fontSize: 13 }, rowValue: { color: "#111827", fontSize: 13, fontWeight: "600", flexShrink: 1, textAlign: "right" }, button: { flexDirection: "row", gap: 8, justifyContent: "center", alignItems: "center", backgroundColor: "#2563EB", padding: 16, borderRadius: 14 }, buttonText: { color: "white", fontWeight: "bold", fontSize: 16 }, homeButton: { padding: 16, alignItems: "center" }, homeText: { color: "#64748B", fontWeight: "600" }, overlay: { flex: 1, backgroundColor: "rgba(0,0,0,.8)", justifyContent: "center", padding: 20 }, ticket: { backgroundColor: "white", borderRadius: 20, padding: 24 }, ticketHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 24 }, brand: { color: "#2563EB", fontWeight: "900", letterSpacing: 1 }, eTicket: { color: "#94A3B8", fontSize: 11, fontWeight: "700" }, ticketRoute: { fontSize: 22, fontWeight: "800", color: "#111827", marginBottom: 20 }, qr: { alignItems: "center", marginTop: 12 }, qrText: { color: "#94A3B8", fontSize: 11, marginTop: 10 }, close: { alignItems: "center", padding: 14, marginTop: 12 }, closeText: { color: "#2563EB", fontWeight: "700" } });
