
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/trackngo?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

trackngo:
  jwt:
    secret: "change-this-secret-change-this-secret"
    expiration-ms: 86400000

